apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-processor-30210
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/core-processor-30210
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
